// <auto-generated />
using System;
using IMS.Plugins.EFCoreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMS.Plugins.EFCoreSql.Migrations
{
    [DbContext(typeof(IMSContext))]
    [Migration("20260128125214_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMS.Core.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74ab7b1f-16ec-426f-9bed-6d35da181a06"),
                            Name = "Bike Seat",
                            Price = 2m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("64ab7b1f-16ec-426f-9bed-6d35da181a06"),
                            Name = "Bike Body",
                            Price = 15m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("54ab7b1f-16ec-426f-9bed-6d35da181a06"),
                            Name = "Bike Wheels",
                            Price = 8m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("44ab7b1f-16ec-426f-9bed-6d35da181a06"),
                            Name = "Bike Pedels",
                            Price = 1m,
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("IMS.Core.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("DoneBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("IMS.Core.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74ab7b1f-16ec-426f-9bed-6d35da181a01"),
                            Name = "Bike",
                            Price = 150m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("74ab7b1f-16ec-426f-9bed-6d35da181a02"),
                            Name = "Car",
                            Price = 1750m,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("IMS.Core.ProductInventory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("ProductInventories");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("74ab7b1f-16ec-426f-9bed-6d35da181a01"),
                            InventoryId = new Guid("74ab7b1f-16ec-426f-9bed-6d35da181a06"),
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = new Guid("74ab7b1f-16ec-426f-9bed-6d35da181a01"),
                            InventoryId = new Guid("64ab7b1f-16ec-426f-9bed-6d35da181a06"),
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = new Guid("74ab7b1f-16ec-426f-9bed-6d35da181a01"),
                            InventoryId = new Guid("54ab7b1f-16ec-426f-9bed-6d35da181a06"),
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = new Guid("74ab7b1f-16ec-426f-9bed-6d35da181a01"),
                            InventoryId = new Guid("44ab7b1f-16ec-426f-9bed-6d35da181a06"),
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("IMS.Core.ProductionTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("DoneBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("int");

                    b.Property<string>("SONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductionTransactions");
                });

            modelBuilder.Entity("IMS.Core.InventoryTransaction", b =>
                {
                    b.HasOne("IMS.Core.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("IMS.Core.ProductInventory", b =>
                {
                    b.HasOne("IMS.Core.Inventory", "Inventory")
                        .WithMany("ProductInventories")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.Core.Product", "Product")
                        .WithMany("ProductInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IMS.Core.ProductionTransaction", b =>
                {
                    b.HasOne("IMS.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IMS.Core.Inventory", b =>
                {
                    b.Navigation("ProductInventories");
                });

            modelBuilder.Entity("IMS.Core.Product", b =>
                {
                    b.Navigation("ProductInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
